### ISSUE TITLE
Sign in again

### ISSUE THREAD

**Issue by 4ev** [rgtk/redmine_impersonate#1]
By clicking on the button "Impersonate".

The term of your session has expired. Please sign in again.

Redmine 3.3.0

**Comment by 4ev** [comment]
Started POST "/admin/impersonation?user_id=8" for IP at 2016-10-10 13:54:48 +0500
Processing by ImpersonationController#create as HTML
  Parameters: {"authenticity_token"=>"enKBY3SmM+tQH+POPPey9owtV2qdiC8Tm/wctXinPOtRy1zf5fR07lUFQh8pwYVB1NPbCAwvTFqcj08RPK7A5g==", "user_id"=>"8"}
  Current user: admin (id=1)
Redirected to http://redmine-test/
Completed 302 Found in 10ms (ActiveRecord: 4.1ms)
Started GET "/" for IP at 2016-10-10 13:54:48 +0500
Processing by WelcomeController#index as HTML
Redirected to http://redmine-test/login?back_url=http%3A%2F%2Fredmine-test%2F
Filter chain halted as :session_expiration rendered or redirected
Completed 302 Found in 6ms (ActiveRecord: 1.2ms)
Started GET "/login?back_url=http%3A%2F%2Fredmine-test%2F" for IP at 2016-10-10 13:54:48 +0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redmine-test/"}
  Current user: anonymous

Completed 200 OK in 45ms (Views: 39.1ms | ActiveRecord: 3.1ms)

**Comment by nounder** [comment]
Thank you for raporting this problem.
I have just pushed new code (c573d40). Please update your repository and try again.
