### ISSUE TITLE
compatibility redmine 4.0 

### ISSUE THREAD

**Issue by slob14** [rgtk/redmine_impersonate#13]
Hi, Thank you for this great plugin.
Tried on Redmine 4.0.2 and it doesn't work
Make a compatibility with Redmine 4.0.x please

Thank you in  advance

**Comment by nounder** [comment]
Plugin is now compatible with Redmine 4 thanks to @antitoine 

You can download it and try.

**Comment by slob14** [comment]
Thank you!!! it is working)
