### ISSUE TITLE
the impersonate banner still showed up for admin user

### ISSUE THREAD

**Issue by iWangJiaxiang** [rgtk/redmine_impersonate#16]
## ENV:

    Redmine version: 4.1.0

## DETAILS:

Hi, I have tested impersonate plugin perfectly with redmine default `admin` account. However, when I used a custom admin account `my_admin`, the impersonate banner would not dispear after clicking `Cancel` button and returning to current `my_admin` account.

Below is a table. I wish it could help you understand me.

Account | What happened when impersonate a user | What happened when cancel impersonating the user
:---: | :---: | :---:
default `admin` | impersonate banner apeared | impersonate banner disapeared
user `my_admin` with admin privilege | impersonate banner apeared |  impersonate banner **still** apeared

Could you please fix this issue?

**Comment by nounder** [comment]
Thanks for this neat write-up. I won't be able to take a look at this issue in foreseeable future.

If some other soul on Internet will deal with it, contribution would be highly appreciated!
