### ISSUE TITLE
Compatibility redmine 5.x

### ISSUE THREAD

**Issue by tza** [rgtk/redmine_impersonate#19]
Hi thanks for the plugin, this is a great help when checking user privileges.
I tested an upgrade on a testsetup, and the plugin is not compatible with the new 5.0.0 release.

Would really appreciate if you could update the master to 5.x compatibility.

**Comment by nounder** [comment]
I’m not using Redmine anymore but I would be more than happy to accept Pull Request that brings 5.x compatibility.

**Comment by sanak** [comment]
@sojitko @tza (CC: @dkastl, @mopinfish)
I am planning to support Redmine 5.0 as part of our @gtt-project work at around next week, so I will make Pull Request to here.

**Comment by nounder** [comment]
@sanak Looking forward to it. Reach out if you need any help! :)

**Comment by sanak** [comment]
@sojitko  
I created the PR (#20), so could you check it ?  
Thanks,

**Comment by nounder** [comment]
#20 merged.

**Comment by jcatrysse** [comment]
This does not seem to work 100%. At first glans, everything seems fine, but permissions are not verified as they should.

I can, for example, freely open projects where the impersonated user is not a member of.

**Comment by jcatrysse** [comment]
> This does not seem to work 100%. At first glans, everything seems fine, but permissions are not verified as they should.
> 
> I can, for example, freely open projects where the impersonated user is not a member of.

This was a configuration error… the user has an ADMIN right… so please ignore.
