### ISSUE TITLE
Update version on redmine.org

### ISSUE THREAD

**Issue by aseques** [rgtk/redmine_impersonate#21]
Your plugin is superuseful, I would like more people to know it, it would be great if you could update the page at https://www.redmine.org/plugins/redmine_impersonate to show current version (2.0.0) instead of 0.9.0, also the changelog show last update on 2015.

**Comment by nounder** [comment]
Glad you find it useful! As per your request, I updated plugin page.

**Comment by aseques** [comment]
Hi, just wanted to let you know that current version works fine with 6.0.9 (not yet updated in redmine page though)
