### ISSUE TITLE
button not working

### ISSUE THREAD

**Issue by cesartrois** [rgtk/redmine_impersonate#3]
Hi;
When i try to use the plugin i had two issues:
1)translation missing: fr.button_impersonate 
2)When i click i got this error:
Page not found

The page you were trying to access doesn't exist or has been removed.
Thank you for your help
Regards

**Comment by nounder** [comment]
1) It is because there is no French translation. English only at this moment. If you would like to help out with it, could you please translate "Impersonate" and "Impersonating" to French :fr: ?
2) On what address did this error occur?

**Comment by cesartrois** [comment]
Hi;
Thank you for your answer.
The url is:
http://192.168.3.200/admin/impersonation?user_id=23
Regards;
Cesar

**Comment by nounder** [comment]
Possibly related to #2.

1. What is the URL of page on which you clicked the button?
2. What is your Redmine version?

**Comment by cesartrois** [comment]
Hi;
1.the url is: http://192.168.3.200/users/23/edit
2. I'm using  a bitnami stack redmine 3.3.1

Thank you

**Comment by nounder** [comment]
Hi. Sorry for long response. This issue somehow got lost in my inbox. From the information you have given me everything should work fine. Maybe there is a problem with server configuration. I tried redmine_impersonate on Bitnami stack and everything works flawlessly. Did you figure out problem by your own now?

**Comment by loogaru** [comment]
Faced the same problem. The reason is very stupid - when installing, I didn't renamed "redmine_impersonate-master" folder to "redmine_impersonate"

**Comment by nounder** [comment]
Thanks for clearing that out :v:
