### ISSUE TITLE
Update README requirements section 

### ISSUE THREAD

**Issue by nounder** [rgtk/redmine_impersonate#8]
After @thegcat contribution (Hello! :wave:), plugin no longer works for 2.x. Time to update requirements section and create separate branch with head 3920cdbb27cce28f99c62b531a99948460c6e013.

Happens after #7.

**Comment by thegcat** [comment]
Please note that sudo mode (#5) requires Redmine 3.1 at least, would that be an acceptable requirement or not?

I would also recommend setting the `require_redmine` in the `init.rb` so that compatibility issues pop up at start time of the Redmine instance instead of subtle breakage at runtime.

**Comment by nounder** [comment]
I'll just `Redmine::VERSION::STRING >= '3.1'` for `require_sudo_mode`.

**Comment by nounder** [comment]
init.rb, README, NEWS updated. Happy Holidays!

**Comment by thegcat** [comment]
Looks great, thanks, happy holidays to you too!
